### ISSUE TITLE
Allow custom extensions in pyramid-get-templates

### ISSUE THREAD

**Issue by hmelman** [dakra/pyramid.el#2]
My templates are using jinja2 but I'm using a .j2 extension on them. It would be nice if `pyramid-get-templates` could be customized to look for .j2 extensions.

**Comment by dakra** [comment]
I made it a defcustom and also added your `.j2` extension.

But the whole template lookup mechanism is still only a "hack"
as I just search for files with those extensions.
Smarter would be to utilize the template engines own python lookup functions.
It's on my todo list (along with pshell support) but
not too easy as it seems the lookup is different for
mako,jinja,chameleon..

Anyway, this should do "for now".
